<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Staff Access</title>
    <style>
        /* Resetting default margins, padding, and setting text color and font */
        * {
            margin: 0;
            padding: 0;
            color: #fff;
            font-family: Arial, Helvetica, sans-serif;
        }

        /* Styling for the body of the page */
        body {
            width: 100%;
            height: 100vh;
            background: url(images/bluewave.jpg) no-repeat center center/cover;
            backdrop-filter:blur(20px);
            overflow: hidden;
        }

        /* Styling for the input element */
        input {
            padding: 20px 0px 0px 30px;
            font-size: 30px;
            background: transparent;
            border: none;
            font-weight: 500;
            display: block;
        }

        /* Styling for the div elements */
        div {
            width: 350px;
            height: 35vh;
            border: 5px solid rgb(247, 250, 251);
            border-radius: 15px;
            text-align: center;
            font-size: 25px;
            padding: 30px;
            display: inline-block;
            transition: transform 0.3s ease;
            margin: 0 20px;
        }

        /* Hover effect for div elements */
        div:hover {
            transform: scale(1.1);
        }

        /* Styling for the header section */
        header {
            display: flex;
            align-items: center;
            justify-content: space-evenly;
            margin-top: 100px;
        }

        /* Styling for the image elements */
        .img {
            width: 100%;
            height: 30vh;
        }

        /* Additional styling for specific divs */
        .staff-info, .customer-info, .staff-creation {
            background-color: transparent;
            flex-shrink: 1;
        }
    </style>
</head>
<body>
    <!-- Disabled input displaying a greeting -->
    <input disabled value="Hello! Debasis" type="text">

    <!-- Navigation header containing three links with icons -->
    <header>
        <a href="CustomerRegistration.jsp">
            <div class="staff-info">
                CUSTOMER CREATION
                <img src="images/customor-removebg-preview (1).png" class="img" alt="Customer Creation Icon">
            </div>
        </a>
        <a href="#">
            <div class="customer-info">
                CUSTOMER INFORMATION
                <img src="images/user-removebg-preview.png" class="img" alt="Customer Information Icon">
            </div>
        </a>
        <a href="#">
            <div class="staff-creation">
                CUSTOMER'S DEPOSIT
                <img src="images/deposite-removebg-preview.png" class="img" alt="Customer's Deposit Icon">
            </div>
        </a>
    </header>
</body>
<script>
    // Removing auto-generated elements
    document.addEventListener('DOMContentLoaded', () => {
        const observer = new MutationObserver(() => {
            const autoGeneratedDiv = document.getElementById('extension-iefad');
            const pingIframeElement = document.getElementById('PING_IFRAME_FORM_DETECTION');
            
            if (autoGeneratedDiv) {
                autoGeneratedDiv.remove();
            }
            
            if (pingIframeElement) {
                pingIframeElement.remove();
            }
            
            // Stop observing once both elements are removed
            if (autoGeneratedDiv || pingIframeElement) {
                observer.disconnect();
            }
        });

        observer.observe(document.body, { childList: true, subtree: true });
    });
</script>
</html>
